"""
generate_snapshot.py — 在 docs/temporary/ 生成代码 + 指标快照。

用法：
    python analyse/generate_snapshot.py --name A2Net_Run1 [--include_metrics]

把 models/ 下所有 .py 文件按固定分隔格式打包成一个 txt（方便整体粘贴给网页 GPT 做参考），
可选地追加 experiment_metrics.xlsx 的指标表。输出到 docs/temporary/。
"""

import os
import argparse

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
OUT_DIR = os.path.join(ROOT, 'docs', 'temporary')


def dump_py_files(base, rel_base, out):
    """Walk base dir, dump every .py under the header block format."""
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in ('__pycache__',)]
        for fn in sorted(filenames):
            if not fn.endswith('.py'):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, rel_base).replace('\\', '\\')
            out.append('=' * 68)
            out.append(f'  {os.path.basename(base)}  |  {rel}')
            out.append('=' * 68)
            out.append('')
            with open(full, encoding='utf-8') as f:
                out.append(f.read().rstrip())
            out.append('')
            out.append('')


def dump_metrics(out):
    """Append experiment_metrics.xlsx as a rough text table."""
    try:
        import openpyxl
    except ImportError:
        out.append('(openpyxl not installed; skip metrics)')
        return
    xlsx = os.path.join(ROOT, 'docs', 'experiment_metrics.xlsx')
    if not os.path.exists(xlsx):
        return
    wb = openpyxl.load_workbook(xlsx, data_only=True)
    out.append('')
    out.append('  EXPERIMENT METRICS (from experiment_metrics.xlsx)')
    for name in wb.sheetnames:
        ws = wb[name]
        out.append('')
        out.append(f'--- Sheet: {name} ---')
        for row in ws.iter_rows(values_only=True):
            cells = ['' if c is None else str(c) for c in row]
            if any(c.strip() for c in cells):
                out.append('\t'.join(cells))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--name', required=True, help='snapshot label, e.g. A2Net_Run1')
    ap.add_argument('--include_metrics', action='store_true', help='also dump xlsx metrics')
    ap.add_argument('--out_dir', default=OUT_DIR)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    out_path = os.path.join(args.out_dir, f'models_and_metrics_{args.name}.txt')

    out = ['', '=' * 68, '  MODELS CODE' + (' + EXPERIMENT METRICS' if args.include_metrics else ''),
           '=' * 68, '', f'Generated by: analyse/generate_snapshot.py', 'Project: LS-Rep_BCD_PLUG',
           '', '']

    models_dir = os.path.join(ROOT, 'models')
    dump_py_files(models_dir, ROOT, out)

    if args.include_metrics:
        dump_metrics(out)

    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out) + '\n')
    print(f'written -> {out_path}')


if __name__ == '__main__':
    main()
